/* Canonical catalog shared by every member-facing page. */
(function () {
    const catalog = [
        { id: "clean-code", title: "Clean Code", author: "Robert C. Martin", category: "programming", categoryLabel: "Programming", isbn: "978-0132350884", published: "2008", publisher: "Prentice Hall", pages: 464, image: "../images/clean-code.jpeg", totalCopies: 5, availableCopies: 5, location: "Main Library – 2nd Floor", shelf: "A-204", rating: "4.8", reviews: "245 Reviews", description: "A handbook of agile software craftsmanship covering clean, readable, and maintainable code." },
        { id: "javascript-definitive-guide", title: "JavaScript: The Definitive Guide", author: "David Flanagan", category: "programming", categoryLabel: "Programming", isbn: "978-1491952023", published: "2020", publisher: "O'Reilly Media", pages: 704, image: "../images/javascript.jpeg", totalCopies: 6, availableCopies: 6, location: "Main Library – 1st Floor", shelf: "P-102", rating: "4.7", reviews: "189 Reviews", description: "A comprehensive reference to JavaScript, browser APIs, and modern web development." },
        { id: "python-crash-course", title: "Python Crash Course", author: "Eric Matthes", category: "programming", categoryLabel: "Programming", isbn: "978-1593279288", published: "2019", publisher: "No Starch Press", pages: 544, image: "../images/python-crash-course.jpeg", totalCopies: 5, availableCopies: 5, location: "Main Library – 1st Floor", shelf: "P-108", rating: "4.8", reviews: "312 Reviews", description: "A hands-on introduction to Python programming and practical projects." },
        { id: "data-structures-algorithms", title: "Data Structures and Algorithms", author: "Michael T. Goodrich", category: "programming", categoryLabel: "Programming", isbn: "978-1118290279", published: "2014", publisher: "Wiley", pages: 768, image: "../images/data-structures.jpeg", totalCopies: 4, availableCopies: 4, location: "Main Library – 2nd Floor", shelf: "A-210", rating: "4.6", reviews: "156 Reviews", description: "An introduction to arrays, trees, graphs, sorting, searching, and algorithm analysis." },
        { id: "introduction-to-algorithms", title: "Introduction to Algorithms", author: "Thomas H. Cormen", category: "programming", categoryLabel: "Programming", isbn: "978-0262033848", published: "2009", publisher: "MIT Press", pages: 1312, image: "../images/introduction-to-algorithms.jpeg", totalCopies: 3, availableCopies: 0, location: "Main Library – 2nd Floor", shelf: "A-215", rating: "4.7", reviews: "278 Reviews", description: "A comprehensive textbook covering fundamental algorithms and data structures." },
        { id: "database-system-concepts", title: "Database System Concepts", author: "Abraham Silberschatz", category: "database", categoryLabel: "Database", isbn: "978-0078022159", published: "2019", publisher: "McGraw-Hill", pages: 1376, image: "../images/database.jpeg", totalCopies: 5, availableCopies: 0, location: "Main Library – 2nd Floor", shelf: "D-301", rating: "4.6", reviews: "198 Reviews", description: "Comprehensive coverage of database architecture, SQL, transactions, and modern data technologies." },
        { id: "the-alchemist", title: "The Alchemist", author: "Paulo Coelho", category: "fiction", categoryLabel: "Fiction", isbn: "978-0062315007", published: "1988", publisher: "HarperOne", pages: 208, image: "../images/alchemist.jpeg", totalCopies: 8, availableCopies: 8, location: "Main Library – Ground Floor", shelf: "F-101", rating: "4.7", reviews: "420 Reviews", description: "A story about dreams, purpose, and the courage to follow a personal legend." },
        { id: "harry-potter-philosophers-stone", title: "Harry Potter and the Philosopher's Stone", author: "J.K. Rowling", category: "fiction", categoryLabel: "Fiction", isbn: "978-0747532699", published: "1997", publisher: "Bloomsbury", pages: 223, image: "../images/harry-potter.jpeg", totalCopies: 10, availableCopies: 10, location: "Main Library – Ground Floor", shelf: "F-115", rating: "4.9", reviews: "520 Reviews", description: "The first journey into Hogwarts and the magical world of Harry Potter." },
        { id: "atomic-habits", title: "Atomic Habits", author: "James Clear", category: "self-development", categoryLabel: "Self Development", isbn: "978-0735211292", published: "2018", publisher: "Avery", pages: 320, image: "../images/atomic-habits.jpeg", totalCopies: 7, availableCopies: 7, location: "Main Library – 1st Floor", shelf: "S-105", rating: "4.8", reviews: "650 Reviews", description: "A practical framework for building good habits and making lasting improvements." },
        { id: "ikigai", title: "Ikigai", author: "Héctor García", category: "self-development", categoryLabel: "Self Development", isbn: "978-0143130727", published: "2016", publisher: "Penguin Books", pages: 208, image: "../images/ikigai.jpeg", totalCopies: 5, availableCopies: 5, location: "Main Library – 1st Floor", shelf: "S-110", rating: "4.6", reviews: "340 Reviews", description: "An exploration of purpose, happiness, and a meaningful life." },
        { id: "computer-networks", title: "Computer Networks", author: "Andrew S. Tanenbaum", category: "networking", categoryLabel: "Networking", isbn: "978-0132126953", published: "2010", publisher: "Pearson", pages: 960, image: "../images/computer-networks.jpeg", totalCopies: 4, availableCopies: 4, location: "Main Library – 2nd Floor", shelf: "N-204", rating: "4.5", reviews: "178 Reviews", description: "A detailed introduction to networking concepts, protocols, and architectures." },
        { id: "operating-system-concepts", title: "Operating System Concepts", author: "Abraham Silberschatz", category: "operating-systems", categoryLabel: "Operating Systems", isbn: "978-1119456339", published: "2018", publisher: "Wiley", pages: 976, image: "../images/operating-system.jpeg", totalCopies: 4, availableCopies: 0, location: "Main Library – 2nd Floor", shelf: "OS-201", rating: "4.6", reviews: "215 Reviews", description: "Fundamental operating-system principles including processes, memory, storage, and security." },
        { id: "artificial-intelligence-modern-approach", title: "Artificial Intelligence: A Modern Approach", author: "Stuart Russell", category: "artificial-intelligence", categoryLabel: "Artificial Intelligence", isbn: "978-0134610993", published: "2021", publisher: "Pearson", pages: 1152, image: "../images/artificial-intelligence.jpeg", totalCopies: 5, availableCopies: 5, location: "Main Library – 3rd Floor", shelf: "AI-301", rating: "4.8", reviews: "289 Reviews", description: "A comprehensive introduction to intelligent agents, machine learning, robotics, and AI." },
        { id: "rich-dad-poor-dad", title: "Rich Dad Poor Dad", author: "Robert T. Kiyosaki", category: "finance", categoryLabel: "Finance", isbn: "978-1612680194", published: "1997", publisher: "Plata Publishing", pages: 336, image: "../images/rich-dad-poor-dad.jpeg", totalCopies: 6, availableCopies: 6, location: "Main Library – 1st Floor", shelf: "F-205", rating: "4.7", reviews: "580 Reviews", description: "An introduction to personal finance, investing, and financial independence." }
    ];

    window.LibraryCatalog = {
        all: () => catalog.map(book => ({ ...book })),
        getById: id => catalog.find(book => book.id === id) || null,
        getByTitle: title => catalog.find(book => book.title === title) || null
    };
}());
